intro: Sinatra Baseline with many goodies

after:
  "Create .gitignore": mv _gitignore .gitignore
  "Run bundle": bundle

params:
  project:
    prompt: "Select project type:"
    type: select
    list: [web, api]
