# frozen_string_literal: true
source "https://rubygems.org"

gem "runfile"
gem "require_all"
gem "awesome_print"

gem "sinatra"
gem "sinatra-contrib"

gem "slim"
gem "puma"
gem "sass"
gem "rack-coffee"

group :development do
  gem "byebug"
  gem "rack-test"
  gem "rspec"
  gem "rspec-html-matchers"
  gem "simplecov"
  gem "runfile-tasks"
end